name: Create Issue
description: Create a github issue on failure or closes that on success
inputs:
  issue_repository:
    description: "The issue repository"
    required: true
    type: string
  issue_type:
    description: "The issue type: FAILURE, SUCCESS"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Checkout this repo
      uses: actions/checkout@v3
      with:
        repository: sigstore/sigstore-probers
        path: sigstore-probers
    - name: Run Create Issue Action
      shell: bash
      run: |
        export ISSUE_REPOSITORY="${{ inputs.issue_repository }}"
        export ISSUE_TYPE="${{ inputs.issue_type }}"
        source sigstore-probers/.github/scripts/create_issue.sh
        create_issue
