version: 2

project_name: sigstore-probers

before:
  hooks:
    - /bin/bash -c 'cd prober && go mod tidy'
    - /bin/bash -c 'if [ -n "$(git --no-pager diff --exit-code go.mod go.sum)" ]; then exit 1; fi'
    - /bin/bash -c 'make release-images'
    - /bin/bash -c 'make sign-release-images'

builds:
  - skip: true

release:
  prerelease: allow
  draft: true
  github:
    owner: sigstore
    name: sigstore-probers
  footer: |
    ### Thanks to all contributors!
