name: Create a github issue on failure or closes that on success
on:
  workflow_call:
    inputs:
      issue_repository:
        description: "The issue repository"
        required: true
        type: string
      issue_type:
        description: "The issue type: FAILURE, SUCCESS"
        required: true
        type: string

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Run Create Issue Action
        run: |
          export ISSUE_REPOSITORY="${{ inputs.issue_repository }}"
          export ISSUE_TYPE="${{ inputs.issue_type }}"
          source .github/scripts/create_issue.sh
          create_issue
