name: Create a github issue on failure
on:
  workflow_call:
    inputs:
      issue_repository:
        description: 'The issue repository'
        required: true
        type: string
jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Run Create Issue Action      
        run: |
          export ISSUE_REPOSITORY="${{ inputs.issue_repository }}"
          source .github/scripts/create_issue.sh
          create_issue